@startuml

class Publication {
String name
int pagesNumber
int year

Publication()
}

class Periodical extends Publication{

inner class Audience{
String name
}


Periodical()
}
@enduml